config/routes.rb
Rails.application.routes.draw do
  resources :incomes

  resources :costs

end

app/models/cost.rb
class Cost < ActiveRecord::Base
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end
  
  def index
   @costs = Cost.all
  @costs_order = Cost.order(category_type: :asc)
  @costs_sum = Cost.sum(:amount)
  @costs_cat = Cost.group(:category_type).sum(:amount)
   @incomes = Income.all
  @incomes_sum = Income.sum(:amount)
  end
  
  
  
   

  

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:date, :category_type, :amount)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end
  
   def index
   @incomes = Income.all
  @incomes_order = Income.order(amount: :asc)
  @incomes_sum = Income.sum(:amount)
  @incomes_inc = Income.group(:category_type).sum(:amount)
  @costs = Cost.all
  @costs_sum = Cost.sum(:amount)
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:date, :category_type, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3><%= f.label :date %><br></h3>
    <%= f.date_select :date %>
  </div>
  <div class="field">
   <h3> <%= f.label :category, class: 'control-label' %><br> </h3>
	<div class="controls">
	<%=f.select(:category_type,options_for_select([['Rent','Rent'],['House','House'],['food','food'],['shopping','shopping'],['car','car'],['entertainment','entertainment'],['miscellaneous','miscellaneous']])) %>
    </div>
  </div>
  <div class="field">
   <h3> <%= f.label :amount %><br></h3>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <h3><%= f.submit %></h3>
  </div>
<% end %>

app/views/costs/edit.html.erb
<body style="background-color:#90EE90">
<center>
<h1 style="color:#663399">Editing cost</h1>

<%= render 'form' %>

<h2 style="color:#FF6347"><%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<body style="background-color:#90EE90">
<center>
<h1 style="color:#663399">Total costs spent on each category</h1>

<table  background-color:blue border="0.75" style="width:50%" border-collapse=collapse>
  <thead>
    <tr>
      <td><h3>Date</h3></td>
      <td><h3>Category</h3></td>
      <td><h3>Amount</h3></td>
      
    </tr>
	<tr>
	  
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.date %></td>
        <td><%= cost.category_type %></td>
        <td><%= cost.amount %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
	  
    <% end %>
	
	
	
	
  </tbody>
  
  <tbody>
   <tr>
   <td><h3>Categories<h3></td>
   <td><h3>Amount<h3> </td>
   </tr>
    <% @costs_cat.each do |key,value| %>
      <tr>
        <td><%= key %></td>
        <td><%= value %></td>
      </tr>
    <% end %>
  </tbody>
  
  <tbody>
  <tr>
	<br>
	<td><h3> Total amount spent :</h3></td>
      <td><h3><%=@costs_sum %></h3></td>
	 </tr>
  </tbody>
  
  <tbody>
  <tr>
	<br>
	<td><h3> Total amount Earned :</h3></td>
      <td><h3><%=@incomes_sum %></h3></td>
	 </tr>
  </tbody>
</table>

<br>

<h2 style="color:#FF6347"> <%= link_to 'New Cost', new_cost_path %></h2>
</center>
</body>

app/views/costs/new.html.erb
<body style="background-color:#90EE90">
<center>
<h1 style="color:#663399">New Cost</h1>
<%= render 'form' %>

<h2 style="color:#FF6347"><%= link_to 'Back', costs_path %> </h2>

app/views/costs/show.html.erb
<body style="background-color:#90EE90">
<center>


<h1 style="color:#663399"><%= notice %></h1>

<p>
<h3>
  <strong>Date:</strong> </h3>  <%= @cost.date %>
 
</p>

<p>
<h3>
  <strong>Category:</strong> </h3>
  <%= @cost.category_type %>

</p>

<p>
<h3>
  <strong>Amount:</strong> </h3>
  <%= @cost.amount %>

</p>

<h2 style="color:#FF6347"><%= link_to 'Edit', edit_cost_path(@cost) %> 
<%= link_to 'Back', costs_path %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <h3> <%= f.label :date %><br></h3>
    <%= f.date_select :date %>
	
  </div>
  <div class="field">
    <h3><%= f.label :category, class: 'control-label' %><br></h3>
	<div class="controls">
	<%=f.select(:category_type,options_for_select([['Salary','Salary'],['Rent','Rent'],['miscellaneous','miscellaneous']])) %>
    </div>
  </div>
  <div class="field">
    <h3><%= f.label :amount %><br></h3>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
   <h3> <%= f.submit %></h3>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<body style="background-color:#90EE90">
<center>
<h1 style="color:#663399">Editing income</h1>

<%= render 'form' %>

<h2 style="color:#FF6347"><%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<body style="background-color:#90EE90">
<center>
<h1 style="color:#663399">Total Incomes earned on each category</h1>

<table  background-color:blue border="0.75" style="width:50%" border-collapse=collapse>
  <thead>
    <tr>
      <td><h3>Date</h3></td>
      <td><h3>Category</h3></td>
      <td><h3>Amount</h3></td>
     
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.date %></td>
        <td><%= income.category_type %></td>
        <td><%= income.amount %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
	
	
  </tbody>
  
  <tbody>
    <tr>
   <td><h3>Categories<h3></td>
   <td><h3>Amount<h3> </td>
    <% @incomes_inc.each do |key,value| %>
      <tr>
        <td><%= key %></td>
        <td><%= value %></td>
      </tr>
    <% end %>
  </tbody>
  
  <tbody>
  <tr>
	
	<td><h3> Total amount Earned :</h3></td>
      <td><h3><%=@incomes_sum %></h3></td></tr>
	  <tr><td><h3> Total amount spent :</h3></td>
      <td><h3><%=@costs_sum %></h3></td>
	 </tr>
  </tbody>
</table>

<br>

<h2 style="color:#FF6347"> <%= link_to 'New Income', new_income_path %></h2>
</center>
</body>

app/views/incomes/new.html.erb
<body style="background-color:#90EE90">
<center>
<h1 style="color:#663399">New Income</h1>

<%= render 'form' %>

<h2 style="color:#FF6347"> <%= link_to 'Back', incomes_path %> </h2>

app/views/incomes/show.html.erb
<body style="background-color:#90EE90">
<center>


<h1 style="color:#663399"><%= notice %></h1>

<p>
  <h3><strong>Date:</strong></h3>
  <%= @income.date %>
</p>

<p>
  <h3><strong>Category:</strong></h3>
  <%= @income.category_type %>
</p>

<p>
  <h3><strong>Amount:</strong></h3>
  <%= @income.amount %>
</p>

<h2 style="color:#FF6347"><%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalletApp</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>